### ISSUE TITLE
Weird spaces between images

### ISSUE THREAD

**Issue by fanalis** [matachines/anilist-collage#1]
This is already known, but if the images don't have the same dimensions, they're are arranged in a way there's a gap between them, like this:

![Image](http://i.imgur.com/H2O3yZL.png)

(I used your username xD)

This can be solved by getting the dimensions of all images, and then cropping to the minimum of them.

The image dimensions can be retrieved using the `identify` command:

    identify -format "%[fx:w]x%[fx:h]" image.jpg  # outputs something like 225x320 (width x height)

Then modify the `montage` command to something like:

    montage -background transparent -tile TILE -geometry +0+0 -crop 225x320+0+0 -gravity center SOURCE_IMAGES OUTPUT_IMAGE

... replacing the `225x320` with the lowest image dimensions.

Hope this helps.

**Comment by matachines** [comment]
Thanks a lot for proposing a solution to this problem. I have fixed the issue using some of your recommendations and the changes are now live. I still see some issues on my own 4x4, but I tried someone else's and it was fine.

**Comment by fanalis** [comment]
Oh, I see. Well, reading the code...

https://github.com/matachines/anilist-collage/blob/aba60caf74dfb903114dc9c53a54f7e2df4876a5/php/functions.php#L45

That will return `false` for `225x320 < 240x300`. I'd treat width and height independently ;)

**Comment by matachines** [comment]
Gotcha. I'll get on that soon, thanks for the heads up.

**Comment by matachines** [comment]
Yup, that fixed everything. Thanks a lot for the contribution.
